### ISSUE TITLE
How to install this in Blender?

### ISSUE THREAD

**Issue by Alan47** [johnzero7/HaydeeTools#1]
I'm interested in using this addon to mod the game. I have the latest stable version of blender installed (2.78c), and tried adding the *.py files via "User Preferences -> Addons -> Install from file...". But no additional import options show up on the UI. Also, the addon is not listed in the addons list. What am I doing wrong here? I also tried zipping all your *.py files into a zip archive and loading that with "Install from file...", but again, nothing happened. Any help on this matter would be much appreciated.

**Comment by johnzero7** [comment]
Try this:
Go to the releaeses page https://github.com/johnzero7/HaydeeTools/releases
download the file HaydeeTools.zip (not the source ones) dont unzipp it.
In blender go to User Preferences -> Addons -> Install from file... and select the downloaded zip
Now you should see ONE addon "Haydee I/O Scripts"
If not, on the top left the is a search field. Type Haydee and the this will filter to should only this addon.
Check the box at the left of the name of the addon to enable it.
Voila. There should be a new panel in the toolpanel called "Haydee" and more option in the export/import menues.
Enjoy

**Comment by Alan47** [comment]
Excellent, working as intended now. Just imported a .mesh file for testing and it looks good in blender! Very nice work! Please consider adding the installation instructions to the `readme.md` of your repository as well.
