### ISSUE TITLE
Not working at all. Can't install in Blender. Many errors.

### ISSUE THREAD

**Issue by Ezovskih** [johnzero7/HaydeeTools#2]

**Comment by johnzero7** [comment]
I see no errors

**Comment by spo702** [comment]
When I tried to enable the mod I got this, and it might possible be what Ezoskih is talking about?
![errorrepportz](https://user-images.githubusercontent.com/22615532/27942460-13b417e4-62a5-11e7-8029-679148cda787.png)

**Comment by johnzero7** [comment]
Probably. Unfortunately at this point, he is the only one that knows.

I hadn't consider the possibility of installing the addon by downloading it from the master branch. I was using releases for that task. But after a little research found out I could just use relative imports to allow instalation from a branch.
Made an update and now should work.
