### ISSUE TITLE
Error while enabling

### ISSUE THREAD

**Issue by Lixsor** [johnzero7/HaydeeTools#4]
![123](https://user-images.githubusercontent.com/50725244/58220415-1c791b80-7d52-11e9-9744-ec7199f463b7.jpg)
I tried to install and enable ver 1.1.2 and it shown me this.
But ver 1.0.6 worked correctly.
Blender ver 2.79

**Comment by Lixsor** [comment]
I tried to install it from zip and after extracting. No effect

**Comment by johnzero7** [comment]
Last version for Blender 2.79 is v1.0.6
All releases after v1.1.0 are for Blender 2.80 (currently in beta)
